from .test_get_list_users import TestGetListUsersMethod
from .test_get_list_users import get_total_users, get_received_response_body_for_ui_list_users, \
    get_request_url_for_ui_list_users
from .test_single_user import get_received_response_body_for_ui_single_user, \
    get_request_url_for_ui_single_user, get_request_url_for_ui_single_user_not_found
from .test_list_resourse import get_received_response_body_for_ui_list_resource, \
    get_request_url_for_ui_list_resource
from .test_single_resource import get_received_response_body_for_ui_single_resource, \
    get_request_url_for_ui_single_resource, get_request_url_for_ui_single_resource_not_found
from .test_delayed_response import get_received_response_body_for_ui_delayed_response, \
    get_request_url_for_ui_delayed_response
from .test_post_create import get_received_response_body_for_ui_post_create, \
    get_request_url_for_ui_post_create
from .test_post_register_successful import get_received_response_body_for_ui_register_successful, \
    get_request_url_for_ui_register_successful
from .test_post_login_successful import get_received_response_body_for_ui_login_successful, \
    get_request_url_for_ui_login_successful
from .test_put_update import get_received_response_body_for_ui_put_update, \
    get_request_url_for_ui_put_update
from .test_patch_update import get_received_response_body_for_ui_patch_update, \
    get_request_url_for_ui_patch_update
from .test_delete_delete import get_received_response_body_for_ui_delete_delete, \
    get_request_url_for_ui_delete_delete
